CREATE DATABASE hw2;
USE hw2;

CREATE TABLE ACCOUNTS (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    SURNAME VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(20) NOT NULL UNIQUE,
    EMAIL VARCHAR(40) NOT NULL UNIQUE,
    PASSWORD VARCHAR(60) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT 0,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT 0
);

CREATE TABLE ARTICLES (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(150) NOT NULL UNIQUE,
    CITY VARCHAR(100) NOT NULL,
    CONTENT TEXT NOT NULL,
    AUTHOR INTEGER NOT NULL,
    IMAGE_URL TEXT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT 0,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT 0,
    FOREIGN KEY (AUTHOR) REFERENCES ACCOUNTS(ID)
);

CREATE TABLE LIKES (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ARTICLE INTEGER NOT NULL,
    AUTHOR INTEGER NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT 0,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT 0,
    FOREIGN KEY (ARTICLE) REFERENCES ARTICLES(ID),
    FOREIGN KEY (AUTHOR) REFERENCES ACCOUNTS(ID)
);

CREATE TABLE FOLLOWS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    FOLLOWER INTEGER NOT NULL,
    FOLLOWED INTEGER NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT 0,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT 0,
    FOREIGN KEY(FOLLOWER) REFERENCES ACCOUNTS(ID),
    FOREIGN KEY(FOLLOWED) REFERENCES ACCOUNTS(ID)
);

CREATE TABLE COMMENTS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    AUTHOR INTEGER NOT NULL,
    CONTENT TEXT NOT NULL,
    ARTICLE INTEGER NOT NULL,
    COMMENT_DATE VARCHAR(10) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT 0,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT 0,
    FOREIGN KEY(AUTHOR) REFERENCES ACCOUNTS(ID),
    FOREIGN KEY(ARTICLE) REFERENCES ARTICLES(ID)
);

